trunk/version-1-0/webapp/django-security-sensor/secapp/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

# Author: Moises Gautier Gomez
# Proyecto fin de carrera - Ing. en Informatica
# Universidad de Granada

app_name = 'secapp'
urlpatterns = [
    # Vista Index
    url(r'^$', views.index, name='index'),

    # Listado de eventos segun la fuente (Source)

    url(r'^(?P<id_log_source>[0-9]+)/event/$', views.events, name='events'),

    # Informacion del paquete asociado a un evento segun la fuente

    url(r'^(?P<id_log_source>[0-9]+)/event/(?P<id_event>[0-9]+)$', views.event_information,
        name='event_information'),

    # Informacion adicional de un paquete asociado a un evento

    url(r'^(?P<id_log_source>[0-9]+)/event/(?P<id_event>[0-9]+)/additional_info/$',
        views.additional_info,
        name='additional_info'),

    # Listado de eventos en formato json almacenados en el sistema para cualquier tipo de fuente (source)

    url(r'^api/events/$', views.EventsInformation().events_list, name='events_list'),

    # Listado de eventos en formato json almacenados en el sistema para una fuente determinada

    url(r'^api/events/by_source/(?P<pk>[0-9]+)/$', views.EventsInformation().events_by_source,
        name='events_by_source'),

    # Evento en formato json almacenado en el sistema para una fuente determinada

    url(r'^api/events/by_source/(?P<pk>[0-9]+)/(?P<fk>[0-9]+)/$', views.EventsInformation().events_by_source_detail,
        name='events_by_source_detail'),

    # Descripcion adicional de un evento en formato json

    url(r'^api/events/(?P<pk>[0-9]+)/additional$', views.EventsInformation().events_detail_additional,
        name='event_detail_additional'),

    # Descripcion completa para un paquete de un evento en formato json

    url(r'^api/packets/(?P<pk>[0-9]+)/(?P<year>[0-9][0-9][0-9][0-9]+)-(?P<month>[0-9][0-9]+)-(?P<day>[0-9][0-9]+)/$',
        views.EventsInformation().packets, name='packets'),

    # Descripcion detallada de un evento en formato json

    url(r'^api/events/(?P<pk>[0-9]+)/json$', views.EventsInformation().event_detail, name='event_detail'),

    # Descripcion detalla de un evento en formato restfull (api django-rest)

    url(r'^api/events/(?P<pk>[0-9]+)/$', views.EventsInformation.as_view()),

    # Lista el numero de eventos de una hora del dia para mostrarlos en las graficas

    url(r'^api/events/hour/(?P<pk>[0-9]+)/$', views.EventsInformation().events_source_in_hour,
        name='events_source_in_hour'),

    # Lista todos los eventos almacenados para un dia

    url(r'^api/events/day/(?P<pk>[0-9]+)/$', views.EventsInformation().events_source_in_day,
        name='events_source_in_day'),

    # Lista todos los eventos de cada hora para una source en las ultimas 24 horas

    url(r'^api/events/day/(?P<pk>[0-9]+)/(?P<year>[0-9][0-9][0-9][0-9]+)-(?P<month>[0-9][0-9]+)-(?P<day>[0-9][0-9]+)/$',
        views.EventsInformation().events_list_in_day, name='events_list_in_day'),

    # Lista todos los eventos almacenados para la semana actual para una determinada fuente

    url(r'^api/events/week/(?P<pk>[0-9]+)/$', views.EventsInformation().events_source_in_week,
        name='events_source_in_week'),

    # Lista todos los eventos almacenados para el mes actual para una determinada fuente
    url(r'^api/events/month/(?P<pk>[0-9]+)/$', views.EventsInformation().events_source_in_month,
        name='events_source_in_month'),

    # Lista todos los eventos almacenados para el year actual para una determinada fuente

    url(r'^api/events/year/(?P<pk>[0-9]+)/$', views.EventsInformation().events_source_in_year,
        name='events_source_in_year'),

    # Lista todos los evento almacenados para el dia anterior a hoy para una determinada fuente

    url(r'^api/events/last_day/(?P<pk>[0-9]+)/$', views.EventsInformation().events_source_last_day,
        name='events_source_last_day'),

    # Lista de todas las entradas de la tabla visualizations en formato json.

    url(r'^api/visualizations/$', views.VisualizationsInformation().list_of_visualizations,
        name='visualizations_list'),

    # Lista de todas las entradas de la tabla visualizations en formato json para la semana actual

    url(r'^api/visualizations/week/$', views.VisualizationsInformation().list_of_visualizations_week,
        name='visualizations_list_week'),

    # Lista de todas las entradas de eventos por dia (semana actual) almacenados para mostrar en la grafica principal

    url(r'^api/visualizations/chart/$', views.VisualizationsInformation().visualizations_chart,
        name='visualizations_chart'),

    # Lista de todas las entradas de eventos por dia almacenados para mostrar en la grafica principal

    url(r'^api/visualizations/(?P<pk>[0-9]+)/chart_all/$', views.VisualizationsInformation().visualizations_chart_all,
        name='visualizations_chart_all'),

    # Listado de estadisticas por cada paquete que se consulte (IPs, Eventos en hora, Puertos, Protocolos, etc)

    url(r'^api/stadistics/(?P<pk>[0-9]+)/(?P<year>[0-9][0-9][0-9][0-9]+)-(?P<month>[0-9][0-9]+)-(?P<day>[0-9][0-9]+)/$',
        views.EventsInformation().stadistics, name='stadistics')

]

urlpatterns = format_suffix_patterns(urlpatterns)

trunk/version-1-0/webapp/django-security-sensor/secapp/templates/secapp/additional_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Additional information</title>
</head>
<body>
<h1>{{ log_source.Type }} - {{ log_source.Description }}</h1>
<h2>{{ event.Timestamp }} - {{ event.Comment }}</h2>
<h3>Additional information of packet event: </h3>
<ul>
    {% for packet in packet_additional_info %}
    <li>
        {{ packet.ID_Tag }} - {{ packet.Value }}
    </li>
    {% endfor %}
</ul>
<p><a href="{% url 'secapp:event_information' log_source.id event.id %}">Events Information</a></p>
</body>
</html>

trunk/version-1-0/webapp/django-security-sensor/secapp/templates/secapp/event_information.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Log Sources</title>
</head>
<body>
{% load handlers %}
<h1>{{ log_source.Type }} - {{ log_source.Description }}</h1>
<h2>
    {{ event.Timestamp }}:{{ event.Timestamp|get_seconds_ts}}.{{ event.Timestamp|get_miliseconds_ts}}
    -
    {{ event.Comment }}
</h2>
<h3>Description of the packet:</h3>
<ul>
    <li>
        IP Source: {{ packet_event_information.ID_IP_Source.Ip }}
    </li>
    <li>
        IP Destiny: {{ packet_event_information.ID_IP_Dest.Ip }}
    </li>
    <li>
        Source Port: {{ packet_event_information.ID_Source_Port }}
    </li>
    <li>
        Destiny Port: {{ packet_event_information.ID_Dest_Port }}
    </li>
    <li>
        Protocol: {{ packet_event_information.Protocol }}
    </li>
    <li>
        Source MAC: {{ packet_event_information.ID_Source_MAC.MAC }}
    </li>
    <li>
        Destiny MAC: {{ packet_event_information.ID_Dest_MAC.MAC }}
    </li>
    <li>
        Tag: {{ packet_event_information.TAG }}
    </li>
</ul>
<p>
    <a href="{% url 'secapp:additional_info' log_source.id event.id %}">Additional information</a>
</p>
<p><a href="{% url 'secapp:events' log_source.id %}">Events</a></p>
</body>
</html>

trunk/version-1-0/webapp/django-security-sensor/secapp/templates/secapp/events.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Events</title>
</head>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script type="text/javascript">
    $('#list-events').delay(800);
</script>
<body>
{% load handlers %}
<h1>{{ log_source.Type }} - {{ log_source.Description }}</h1>
<h3>
    List of events:
</h3>
<div id="list-events">
<ul>
    {% for item in events_list %}
    <li>
        <a href="{% url 'secapp:event_information' log_source.id item.id %}">
            {{ item.Timestamp }}:{{ item.Timestamp|get_seconds_ts}}.{{ item.Timestamp|get_miliseconds_ts}}
            -
            {{ item.Comment }}
        </a>
    </li>
    {% endfor %}
</ul>
</div>
<p><a href="{% url 'secapp:index' %}">Index</a></p>
</body>
</html>

trunk/version-1-0/webapp/django-security-sensor/secapp/templates/secapp/index.html
{% extends 'MasterPages/MasterPage.html' %}
{% block title %}Home{% endblock %}
{% block content %}

<div id="content"></div>

<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>

<div class="row">
    <div class="col-md-2"></div>
<div class="col-md-3" id="update-events" style="display:none">
    <span style="margin-left:1em">Update events table: </span>
    <button id="update-events-button" type="button" class="btn btn-default btn-sm">
        <span class="glyphicon glyphicon-refresh"></span>
    </button>
</div>
    <div class="col-md-7"></div>
</div>
<div class="row">
    <div class="col-md-7">
<table id="events-table" class="display" style="display:none" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Packet</th>
                <th>Event</th>
                <th>Timestamp</th>
                <th>Comment</th>
                <th>SIP</th>
                <th>DIP</th>
                <th>SPort</th>
                <th>DPort</th>
                <th>Protocol</th>
                <th>SMAC</th>
                <th>DMAC</th>
                <th>TAG</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>Packet</th>
                <th>Event</th>
                <th>Timestamp</th>
                <th>Comment</th>
                <th>SIP</th>
                <th>DIP</th>
                <th>SPort</th>
                <th>DPort</th>
                <th>Protocol</th>
                <th>SMAC</th>
                <th>DMAC</th>
                <th>TAG</th>
            </tr>
        </tfoot>
    </table>
    </div>
    <div class="col-md-5">
        <div id="live" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
        <div id="interaction" style="display: none">
            <select id="stadistics-select" name="stadistics-select">
                <option value="-" selected>-</option>
                <option value="SIP">Source Ip</option>
                <option value="DIP">Destination Ip</option>
                <option value="SPORT">Source Port</option>
                <option value="DPORT">Destination Port</option>
                <option value="Timestamps">Timestamp</option>
                <option value="Protocol">Protocol</option>
            </select>
            <span style="margin-left:1em">Get stadistics</span>
            <button id="stadistics-show-button" type="button" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-repeat"></span>
            </button>
        </div>
        <div id="stadistics" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
    </div>
    </div>

{% endblock %}